#ifndef BIOSIM_CORE_STATUS_H
#define BIOSIM_CORE_STATUS_H

typedef enum {
    BIOSIM_OK = 0,
    BIOSIM_ERR_NOMEM,
    BIOSIM_ERR_TYPE,
    BIOSIM_ERR_NOTFOUND,
    BIOSIM_ERR_INVALID,
    BIOSIM_ERR_IO,
    BIOSIM_WARN_UNKNOWN_KEY,
} biosim_status_t;

#endif /* BIOSIM_CORE_STATUS_H */
