#include "biosim/sim-gpu/registry.h"
#include "biosim/core/log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── embedded preamble strings ──────────────────────────────────────────── */

/* Generated by biosim_embed_opencl_source() in sim-gpu's CMakeLists.txt. */
extern const char biosim_gpu_preamble_types_h[];
extern const char biosim_gpu_preamble_rng_h[];
extern const char biosim_gpu_preamble_gene_h[];
extern const char biosim_gpu_preamble_io_defs_h[];
extern const char biosim_gpu_preamble_challenge_kinds_h[];

/* ── embedded kernel strings ────────────────────────────────────────────── */

extern const char biosim_gpu_k1_feedforward[];
extern const char biosim_gpu_k2_kill_marked[];
extern const char biosim_gpu_k3_movement_resolution[];
extern const char biosim_gpu_k4_signal_fade[];
extern const char biosim_gpu_k5_challenge_step_eval[];

/* ── kernel table ───────────────────────────────────────────────────────── */

typedef struct {
    const char *name;
    const char *embedded_source;
} biosim_kernel_entry_t;

static const biosim_kernel_entry_t KERNEL_TABLE[] = {
    {"k1_feedforward", biosim_gpu_k1_feedforward},
    {"k2_kill_marked", biosim_gpu_k2_kill_marked},
    {"k3_movement_resolution", biosim_gpu_k3_movement_resolution},
    {"k4_signal_fade", biosim_gpu_k4_signal_fade},
    {"k5_challenge_step_eval", biosim_gpu_k5_challenge_step_eval},
};

#define KERNEL_TABLE_COUNT (sizeof(KERNEL_TABLE) / sizeof(KERNEL_TABLE[0]))

/* ── filesystem override ─────────────────────────────────────────────────── */

static biosim_status_t load_override(const char *exec_dir, const char *kernel_name,
                                     char **buf_out) {
    char path[4096];
    int written = snprintf(path, sizeof(path), "%s/%s.cl", exec_dir, kernel_name);
    if (written < 0 || (size_t)written >= sizeof(path)) {
        return BIOSIM_ERR_NOTFOUND;
    }

    FILE *f = fopen(path, "rb");
    if (!f) {
        return BIOSIM_ERR_NOTFOUND;
    }

    biosim_status_t returncode = BIOSIM_OK;
    char *buf = NULL;

    if (fseek(f, 0, SEEK_END) != 0) {
        returncode = BIOSIM_ERR_IO;
        goto exit;
    }
    long size = ftell(f);
    if (size < 0) {
        returncode = BIOSIM_ERR_IO;
        goto exit;
    }
    if (fseek(f, 0, SEEK_SET) != 0) {
        returncode = BIOSIM_ERR_IO;
        goto exit;
    }

    buf = malloc((size_t)size + 1U);
    if (!buf) {
        returncode = BIOSIM_ERR_NOMEM;
        goto exit;
    }

    if (fread(buf, 1U, (size_t)size, f) != (size_t)size) {
        returncode = BIOSIM_ERR_IO;
        goto exit;
    }
    buf[(size_t)size] = '\0';
    *buf_out = buf;

exit:
    if (returncode != BIOSIM_OK) {
        free(buf);
        BIOSIM_ERRORF("registry: failed to load override %s (%s)", path,
                      biosim_strerror(returncode));
    }
    (void)fclose(f);
    return returncode;
}

/* ── public API ─────────────────────────────────────────────────────────── */

void biosim_gpu_kernel_sources_free(biosim_gpu_kernel_sources_t *s) {
    if (!s) {
        return;
    }
    free(s->override_buf);
    memset(s, 0, sizeof(*s));
}

biosim_status_t biosim_gpu_registry_get(const char *kernel_name, const char *exec_dir,
                                        biosim_gpu_kernel_sources_t *out) {
    const biosim_kernel_entry_t *entry = NULL;
    for (size_t i = 0U; i < KERNEL_TABLE_COUNT; i++) {
        if (strcmp(KERNEL_TABLE[i].name, kernel_name) == 0) {
            entry = &KERNEL_TABLE[i];
            break;
        }
    }
    if (!entry) {
        BIOSIM_ERRORF("registry: unknown kernel '%s'", kernel_name);
        return BIOSIM_ERR_NOTFOUND;
    }

    memset(out, 0, sizeof(*out));
    out->sources[0] = biosim_gpu_preamble_types_h;
    out->sources[1] = biosim_gpu_preamble_rng_h;
    out->sources[2] = biosim_gpu_preamble_gene_h;
    out->sources[3] = biosim_gpu_preamble_io_defs_h;
    out->sources[4] = biosim_gpu_preamble_challenge_kinds_h;
    out->count = BIOSIM_GPU_MAX_SOURCES;

    if (exec_dir) {
        char *buf = NULL;
        biosim_status_t rc = load_override(exec_dir, kernel_name, &buf);
        if (rc == BIOSIM_OK) {
            out->sources[BIOSIM_GPU_PREAMBLE_COUNT] = buf;
            out->override_buf = buf;
            BIOSIM_INFOF("registry: loaded filesystem override for '%s'", kernel_name);
            return BIOSIM_OK;
        }
        if (rc != BIOSIM_ERR_NOTFOUND) {
            return rc;
        }
        /* BIOSIM_ERR_NOTFOUND just means no override file — fall through */
    }

    out->sources[BIOSIM_GPU_PREAMBLE_COUNT] = entry->embedded_source;
    return BIOSIM_OK;
}
